name: Markdown to PDF

on:
  push:
    branches: [ "main" ]

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive

      - name: Install Natex
        run: sudo apt-get install texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc markdown_electrónica.md -o markdown_electrónica.pdf --pdf-engine=xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: hardware-electronica.pdf
